// Code generated by "stringer -type=astType"; DO NOT EDIT.

package main

import "strconv"

const _astType_name = "AtomListIntFloatString"

var _astType_index = [...]uint8{0, 4, 8, 11, 16, 22}

func (i astType) String() string {
	if i < 0 || i >= astType(len(_astType_index)-1) {
		return "astType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _astType_name[_astType_index[i]:_astType_index[i+1]]
}
