// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package main

import "strconv"

const _tokenType_name = "LParenTokRParenTokAtomTokIntTokFloatTokStringTokQuoteTokQuasiQuoteTokUnquoteTok"

var _tokenType_index = [...]uint8{0, 9, 18, 25, 31, 39, 48, 56, 69, 79}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
